### ISSUE TITLE
renderer is showing error at the time of verify document

### ISSUE THREAD

**Issue by vaibhavpawarautomaxis** [TradeTrust/generic-templates#110]
Below is screenshot and .tt file which we are trying to verify.

`const documentBases = {
    "$template": {
      "name": "INVOICE",
      "type": "EMBEDDED_RENDERER",
      "url": "https://generictemplates.fdpconnect.com"
    },
    "recipient": {
      "name": "John Doe"
    },
    "issuers": [
      {
        "name": "Demo Issuer",
        "documentStore": documentStoreAddress,
        "identityProof": {
          "type": "DNS-TXT",
          "location": locations,
        }
      }
    ]
  }`

![Screenshot 2024-02-01 105951](https://github.com/TradeTrust/generic-templates/assets/152165841/f4e166be-a2a6-4124-ac3f-0ac099ee5914)

`{"version":"https://schema.openattestation.com/2.0/schema.json","data":{"$template":{"name":"1631158d-17d0-494b-b9fa-9d9ab6b40b49:string:INVOICE","type":"b5231cd4-90c0-4d7a-bab4-666345590cbb:string:EMBEDDED_RENDERER","url":"c050efaf-55e3-4c32-86cd-bf45b1e98d84:string:https://generictemplates.fdpconnect.com"},"recipient":{"name":"907f3ea7-765f-438a-80e8-efa768efb759:string:John Doe"},"issuers":[{"name":"896a46ad-a583-494c-a96c-db012c46a3b3:string:Demo Issuer","documentStore":"08317949-bde4-4fe9-9c92-bc295a222e85:string:0xCef03835d4a4dCEa5cAeE462b1703E12DFd3c1aa","identityProof":{"type":"11dfde32-681c-48f5-82e7-0fd51dcfed60:string:DNS-TXT","location":"1cb78d34-1906-4dd2-aab1-e604605de127:string:exporterfdp-befuddledknocker.fdpconnect.com"}}],"id":"798db861-e07b-472f-9070-29a603cdd19f:string:CF/01062","tax":"488573e8-a6cc-42d9-895a-85b67443d1b2:string:","date":"e3c8884e-ac22-466f-9b89-b0bb0871a942:string:","terms":"b1c001fa-4447-4b06-99b4-22e5346abdfb:string:","total":"cb656cf6-7a44-462e-ad03-ad0164233fb9:string:17,700.00","billTo":{"name":"a5af3a78-a0a0-47f9-a248-e2d77d253893:string:","email":"77367c53-1a87-4333-9907-9f0c21627814:string:","company":{"city":"b98c433e-731b-4926-ab7d-7b3cebcfa49a:string:","name":"ea6ff48d-f1cd-4a74-91ab-4bb13b9594e7:string:","postalCode":"25ee8dd3-389d-4d41-b082-717b0ecaea42:string:","phoneNumber":"8fda5062-3eb7-4e57-aebb-066ae7cea00c:string:","streetAddress":"ef348dd3-adb8-4bd8-9888-19c370fb797c:string:"}},"billFrom":{"city":"7403a221-1dbc-45e3-8c38-c44b8b8240cd:string:","name":"965e9bf2-c8c2-4bcd-a142-6f1b853dca18:string:","postalCode":"721cd88d-dba3-4d9b-8ad3-bfe51c3072f3:string:","phoneNumber":"707e4124-3df4-481b-82b7-754314ecf2b4:string:","streetAddress":"534b106d-41c9-4277-b363-3de3ef7ab8d3:string:"},"subtotal":"510732ae-86e4-44da-8c9f-a12a5b11a15b:string:","taxTotal":"d6750d71-406b-4c49-a257-4f166a185f2c:string:","customerId":"87473390-7945-4d13-9a1c-83f1d61cc7a1:string:","billableItems":[{"amount":"34128be8-fd54-4507-a2f7-dd9a76558946:string:10,200.00 ","quantity":"7b9ff974-7171-4b4a-aa3a-2f2401715e11:string:255.00 ","unitPrice":"41adab72-6ea4-405f-99f6-2841ad58a2bf:string:40.00 ","description":"8d402bd7-018f-4043-9728-469814e62492:string:TMS Employee charges for the month of June 23 "},{"amount":"b6b285db-bbf4-4d52-b8a8-0b927b19282f:string:7,500.00 ","quantity":"6e91e755-86e7-4007-8634-58bce781dda8:string:5.00 Nos ","unitPrice":"2d895d6c-6a4a-4bd3-a514-b995ddf34402:string:1,500.00 ","description":"411306e4-cbc4-46ef-8761-41e00fc718c3:string:IVR PORTS "},{"amount":"38416f40-0b02-4d04-a652-2ec843ecb865:string:17,700.00 ","quantity":"678d182c-0956-4bb7-8170-38a87bfc1c72:string:","unitPrice":"58eb5d0b-8a0f-48a8-8d6b-985c3f053970:string:Sub Total ","description":"f5feec7e-a19c-402d-8ddb-f8849c4c7226:string:"},{"amount":"05113e69-1cb4-4fb9-96c3-5a6d38774e18:string:17,700.00 ","quantity":"479581af-df32-418c-98bb-cf762fc29f9f:string:","unitPrice":"3d8af7fb-e848-4c60-b4ce-ef58751530e1:string:Total ","description":"9a2e4aae-9ba6-48f4-b631-0feb80c31ccf:string:In Words Rupee Seventeen Thousand Seven Hundred Only "},{"amount":"45473360-0861-4867-998f-6730ee5a7b0d:string:17,700.00 ","quantity":"b36339f0-7341-4337-96d9-ab0cd5187599:string:Balance ","unitPrice":"67cc649e-1e38-49c9-b5de-80c82be6634f:string:Due ","description":"b41ea569-7678-4eec-b93a-ca16c9bd1ca6:string:"}],"shippingBillNumber":"3ffc04bb-746a-45a3-92ad-bbb2b1a28a51:string:"},"signature":{"type":"SHA3MerkleProof","targetHash":"1b8b5ef97d4c499936b2b2ee615b6a0266851447a8d1836b77f4c6974e1786dd","proof":[],"merkleRoot":"1b8b5ef97d4c499936b2b2ee615b6a0266851447a8d1836b77f4c6974e1786dd"}}`

**Comment by isaackps** [comment]
Hi,

I can see that it is a connection time out, but im not sure if it is due to CORS issue as i have no visibility on your application that you hosted in that url. Could you double check the timeout issue? it shouldn't be on our verifier site.

**Comment by Mapuppy09** [comment]
Soy Nueva en esto y no entiendo mucho , si hay un error , por favor que tengo que hacer.Gracias!

**Comment by pohhendry** [comment]
@vaibhavpawarautomaxis from what I understand, you have successfully resolved the issue. If not, please open a new issue to document your issue.

Thank you.

**Comment by Mapuppy09** [comment]
Yes Thanks!

Mayra delapaz
