### ISSUE TITLE
Error 110 

### ISSUE THREAD

**Issue by Mapuppy09** [TradeTrust/generic-templates#118]
Por favor verificar , no entiendo que esta erroneo

**Comment by pohhendry** [comment]
Hi @Mapuppy09, we would greatly appreciate it if you could follow the guidelines we have in place for contributing, as this will positively impact the community.

https://github.com/TradeTrust/tradetrust-website/blob/master/CONTRIBUTING.md

**Comment by Mapuppy09** [comment]
Thanks !
